apiVersion: v1
kind: Service
metadata:
  name: sercure-message-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: secure-message-service